---
- name: Import install kit
  include_tasks: "install_kit.yml"

- name: Generate parameter file for sapinst
  template:
      src: sapinst.cfg
      dest: "{{ s4app_kit }}/inifile.params"

- name: Check if S/4HANA Application Server was already installed
  stat:
    path: "/sapmnt/{{ sap_sid|upper }}/exe/uc/linuxx86_64/SAPCAR"
  register: install_status

- name: Start SAP S/4HANA Application Server installation
  shell: >-
    {{ s4app_kit }}/swpm/sapinst SAPINST_INPUT_PARAMETERS_URL={{ s4app_kit }}/inifile.params
    SAPINST_EXECUTE_PRODUCT_ID={{ sap_product_id }} SAPINST_SKIP_DIALOGS=true SAPINST_START_GUISERVER=false
  when: not install_status.stat.exists

- name: Cleanup
  file:
    path: "{{ s4app_kit }}"
    state: absent
...
