---
saphana_required_packages:
  - expect
  - krb5-workstation
  - krb5-libs
  - libaio
  - libcanberra-gtk2
  - libicu
  - libssh2
  - libtool-ltdl
  - numactl
  - openssl
  - PackageKit-gtk3-module
  - rsyslog
  - sudo
  - tcsh
  - rsyslog
  - xorg-x11-xauth
  - xulrunner
  - gtk2
  - cairo
  - graphviz
  - iptraf-ng
  - lm_sensors
  - nfs-utils
  - bind-utils
  - net-tools
  - compat-sap-c++-9
  - libatomic
  - chrony

saphana_required_package_groups:
  - "@base"

saphana_required_configurations:
  - "repository_RedHat"
  - "update_RedHat7"
  - "reqpkggroups_RedHat"
  - "reqpkg"
  - "hostname_fix_RedHat"
  - "hostname"
  - "filesystems"
  - "tuned"
  - "SELinux"
  - "firewalld"
  - "symlinks"
  - "abrtd"
  - "kdump"
  - "limits"
  - "tmpfiles"
  - "kernel_RedHat7"
  - "reboot"
...
